/**
 * Supported currencies list
 */
rciSpaApp.factory('openExchange', function($http) {
    var OPEN_EXCHANGE_API_URL = 'https://openexchangerates.org/api/';
    var APP_ID = '68f8c549dee745dd9582e254c3686438';

    function getCurrencies() {
        return {
            "AED": "United Arab Emirates Dirham",
            "AFN": "Afghan Afghani",
            "ALL": "Albanian Lek",
            "AMD": "Armenian Dram",
            "ANG": "Netherlands Antillean Guilder",
            "AOA": "Angolan Kwanza",
            "ARS": "Argentine Peso",
            "AUD": "Australian Dollar",
            "AWG": "Aruban Florin",
            "AZN": "Azerbaijani Manat",
            "BAM": "Bosnia-Herzegovina Convertible Mark",
            "BBD": "Barbadian Dollar",
            "BDT": "Bangladeshi Taka",
            "BGN": "Bulgarian Lev",
            "BHD": "Bahraini Dinar",
            "BIF": "Burundian Franc",
            "BMD": "Bermudan Dollar",
            "BND": "Brunei Dollar",
            "BOB": "Bolivian Boliviano",
            "BRL": "Brazilian Real",
            "BSD": "Bahamian Dollar",
            "BTC": "Bitcoin",
            "BTN": "Bhutanese Ngultrum",
            "BWP": "Botswanan Pula",
            "BYR": "Belarusian Ruble",
            "BZD": "Belize Dollar",
            "CAD": "Canadian Dollar",
            "CDF": "Congolese Franc",
            "CHF": "Swiss Franc",
            "CLF": "Chilean Unit of Account (UF)",
            "CLP": "Chilean Peso",
            "CNY": "Chinese Yuan",
            "COP": "Colombian Peso",
            "CRC": "Costa Rican Colón",
            "CUP": "Cuban Peso",
            "CVE": "Cape Verdean Escudo",
            "CZK": "Czech Republic Koruna",
            "DJF": "Djiboutian Franc",
            "DKK": "Danish Krone",
            "DOP": "Dominican Peso",
            "DZD": "Algerian Dinar",
            "EEK": "Estonian Kroon",
            "EGP": "Egyptian Pound",
            "ETB": "Ethiopian Birr",
            "EUR": "Euro",
            "FJD": "Fijian Dollar",
            "FKP": "Falkland Islands Pound",
            "GBP": "British Pound Sterling",
            "GEL": "Georgian Lari",
            "GHS": "Ghanaian Cedi",
            "GIP": "Gibraltar Pound",
            "GMD": "Gambian Dalasi",
            "GNF": "Guinean Franc",
            "GTQ": "Guatemalan Quetzal",
            "GYD": "Guyanaese Dollar",
            "HKD": "Hong Kong Dollar",
            "HNL": "Honduran Lempira",
            "HRK": "Croatian Kuna",
            "HTG": "Haitian Gourde",
            "HUF": "Hungarian Forint",
            "IDR": "Indonesian Rupiah",
            "ILS": "Israeli New Sheqel",
            "INR": "Indian Rupee",
            "IQD": "Iraqi Dinar",
            "IRR": "Iranian Rial",
            "ISK": "Icelandic Króna",
            "JEP": "Jersey Pound",
            "JMD": "Jamaican Dollar",
            "JOD": "Jordanian Dinar",
            "JPY": "Japanese Yen",
            "KES": "Kenyan Shilling",
            "KGS": "Kyrgystani Som",
            "KHR": "Cambodian Riel",
            "KMF": "Comorian Franc",
            "KPW": "North Korean Won",
            "KRW": "South Korean Won",
            "KWD": "Kuwaiti Dinar",
            "KYD": "Cayman Islands Dollar",
            "KZT": "Kazakhstani Tenge",
            "LAK": "Laotian Kip",
            "LBP": "Lebanese Pound",
            "LKR": "Sri Lankan Rupee",
            "LRD": "Liberian Dollar",
            "LSL": "Lesotho Loti",
            "LTL": "Lithuanian Litas",
            "LVL": "Latvian Lats",
            "LYD": "Libyan Dinar",
            "MAD": "Moroccan Dirham",
            "MDL": "Moldovan Leu",
            "MGA": "Malagasy Ariary",
            "MKD": "Macedonian Denar",
            "MMK": "Myanma Kyat",
            "MNT": "Mongolian Tugrik",
            "MOP": "Macanese Pataca",
            "MRO": "Mauritanian Ouguiya",
            "MTL": "Maltese Lira",
            "MUR": "Mauritian Rupee",
            "MVR": "Maldivian Rufiyaa",
            "MWK": "Malawian Kwacha",
            "MXN": "Mexican Peso",
            "MYR": "Malaysian Ringgit",
            "MZN": "Mozambican Metical",
            "NAD": "Namibian Dollar",
            "NGN": "Nigerian Naira",
            "NIO": "Nicaraguan Córdoba",
            "NOK": "Norwegian Krone",
            "NPR": "Nepalese Rupee",
            "NZD": "New Zealand Dollar",
            "OMR": "Omani Rial",
            "PAB": "Panamanian Balboa",
            "PEN": "Peruvian Nuevo Sol",
            "PGK": "Papua New Guinean Kina",
            "PHP": "Philippine Peso",
            "PKR": "Pakistani Rupee",
            "PLN": "Polish Zloty",
            "PYG": "Paraguayan Guarani",
            "QAR": "Qatari Rial",
            "RON": "Romanian Leu",
            "RSD": "Serbian Dinar",
            "RUB": "Russian Ruble",
            "RWF": "Rwandan Franc",
            "SAR": "Saudi Riyal",
            "SBD": "Solomon Islands Dollar",
            "SCR": "Seychellois Rupee",
            "SDG": "Sudanese Pound",
            "SEK": "Swedish Krona",
            "SGD": "Singapore Dollar",
            "SHP": "Saint Helena Pound",
            "SLL": "Sierra Leonean Leone",
            "SOS": "Somali Shilling",
            "SRD": "Surinamese Dollar",
            "STD": "São Tomé and Príncipe Dobra",
            "SVC": "Salvadoran Colón",
            "SYP": "Syrian Pound",
            "SZL": "Swazi Lilangeni",
            "THB": "Thai Baht",
            "TJS": "Tajikistani Somoni",
            "TMT": "Turkmenistani Manat",
            "TND": "Tunisian Dinar",
            "TOP": "Tongan Paʻanga",
            "TRY": "Turkish Lira",
            "TTD": "Trinidad and Tobago Dollar",
            "TWD": "New Taiwan Dollar",
            "TZS": "Tanzanian Shilling",
            "UAH": "Ukrainian Hryvnia",
            "UGX": "Ugandan Shilling",
            "USD": "United States Dollar",
            "UYU": "Uruguayan Peso",
            "UZS": "Uzbekistan Som",
            "VEF": "Venezuelan Bolívar Fuerte",
            "VND": "Vietnamese Dong",
            "VUV": "Vanuatu Vatu",
            "WST": "Samoan Tala",
            "XAF": "CFA Franc BEAC",
            "XAG": "Silver (troy ounce)",
            "XAU": "Gold (troy ounce)",
            "XCD": "East Caribbean Dollar",
            "XDR": "Special Drawing Rights",
            "XOF": "CFA Franc BCEAO",
            "XPF": "CFP Franc",
            "YER": "Yemeni Rial",
            "ZAR": "South African Rand",
            "ZMK": "Zambian Kwacha (pre-2013)",
            "ZMW": "Zambian Kwacha",
            "ZWL": "Zimbabwean Dollar"
        }
    }

    function getCurrenciesWithAbbrName() {
        return {
            "AED": "(AED) United Arab Emirates Dirham",
            "AFN": "(AFN) Afghan Afghani",
            "ALL": "(ALL) Albanian Lek",
            "AMD": "(AMD) Armenian Dram",
            "ANG": "(ANG) Netherlands Antillean Guilder",
            "AOA": "(AOA) Angolan Kwanza",
            "ARS": "(ARS) Argentine Peso",
            "AUD": "(AUD) Australian Dollar",
            "AWG": "(AWG) Aruban Florin",
            "AZN": "(AZN) Azerbaijani Manat",
            "BAM": "(BAM) Bosnia-Herzegovina Convertible Mark",
            "BBD": "(BBD) Barbadian Dollar",
            "BDT": "(BDT) Bangladeshi Taka",
            "BGN": "(BGN) Bulgarian Lev",
            "BHD": "(BHD) Bahraini Dinar",
            "BIF": "(BIF) Burundian Franc",
            "BMD": "(BMD) Bermudan Dollar",
            "BND": "(BND) Brunei Dollar",
            "BOB": "(BOB) Bolivian Boliviano",
            "BRL": "(BRL) Brazilian Real",
            "BSD": "(BSD) Bahamian Dollar",
            "BTC": "(BTC) Bitcoin",
            "BTN": "(BTN) Bhutanese Ngultrum",
            "BWP": "(BWP) Botswanan Pula",
            "BYR": "(BYR) Belarusian Ruble",
            "BZD": "(BZD) Belize Dollar",
            "CAD": "(CAD) Canadian Dollar",
            "CDF": "(CDF) Congolese Franc",
            "CHF": "(CHF) Swiss Franc",
            "CLF": "(CLF) Chilean Unit of Account (UF)",
            "CLP": "(CLP) Chilean Peso",
            "CNY": "(CNY) Chinese Yuan",
            "COP": "(COP) Colombian Peso",
            "CRC": "(CRC) Costa Rican Colón",
            "CUP": "(CUP) Cuban Peso",
            "CVE": "(CVE) Cape Verdean Escudo",
            "CZK": "(CZK) Czech Republic Koruna",
            "DJF": "(DJF) Djiboutian Franc",
            "DKK": "(DKK) Danish Krone",
            "DOP": "(DOP) Dominican Peso",
            "DZD": "(DZD) Algerian Dinar",
            "EEK": "(EEK) Estonian Kroon",
            "EGP": "(EGP) Egyptian Pound",
            "ETB": "(ETB) Ethiopian Birr",
            "EUR": "(EUR) Euro",
            "FJD": "(FJD) Fijian Dollar",
            "FKP": "(FKP) Falkland Islands Pound",
            "GBP": "(GBP) British Pound Sterling",
            "GEL": "(GEL) Georgian Lari",
            "GHS": "(GHS) Ghanaian Cedi",
            "GIP": "(GIP) Gibraltar Pound",
            "GMD": "(GMD) Gambian Dalasi",
            "GNF": "(GNF) Guinean Franc",
            "GTQ": "(GTQ) Guatemalan Quetzal",
            "GYD": "(GYD) Guyanaese Dollar",
            "HKD": "(HKD) Hong Kong Dollar",
            "HNL": "(HNL) Honduran Lempira",
            "HRK": "(HRK) Croatian Kuna",
            "HTG": "(HTG) Haitian Gourde",
            "HUF": "(HUF) Hungarian Forint",
            "IDR": "(IDR) Indonesian Rupiah",
            "ILS": "(ILS) Israeli New Sheqel",
            "INR": "(INR) Indian Rupee",
            "IQD": "(IQD) Iraqi Dinar",
            "IRR": "(IRR) Iranian Rial",
            "ISK": "(ISK) Icelandic Króna",
            "JEP": "(JEP) Jersey Pound",
            "JMD": "(JMD) Jamaican Dollar",
            "JOD": "(JOD) Jordanian Dinar",
            "JPY": "(JPY) Japanese Yen",
            "KES": "(KES) Kenyan Shilling",
            "KGS": "(KGS) Kyrgystani Som",
            "KHR": "(KHR) Cambodian Riel",
            "KMF": "(KMF) Comorian Franc",
            "KPW": "(KPW) North Korean Won",
            "KRW": "(KRW) South Korean Won",
            "KWD": "(KWD) Kuwaiti Dinar",
            "KYD": "(KYD) Cayman Islands Dollar",
            "KZT": "(KZT) Kazakhstani Tenge",
            "LAK": "(LAK) Laotian Kip",
            "LBP": "(LBP) Lebanese Pound",
            "LKR": "(LKR) Sri Lankan Rupee",
            "LRD": "(LRD) Liberian Dollar",
            "LSL": "(LSL) Lesotho Loti",
            "LTL": "(LTL) Lithuanian Litas",
            "LVL": "(LVL) Latvian Lats",
            "LYD": "(LYD) Libyan Dinar",
            "MAD": "(MAD) Moroccan Dirham",
            "MDL": "(MDL) Moldovan Leu",
            "MGA": "(MGA) Malagasy Ariary",
            "MKD": "(MKD) Macedonian Denar",
            "MMK": "(MMK) Myanma Kyat",
            "MNT": "(MNT) Mongolian Tugrik",
            "MOP": "(MOP) Macanese Pataca",
            "MRO": "(MRO) Mauritanian Ouguiya",
            "MTL": "(MTL) Maltese Lira",
            "MUR": "(MUR) Mauritian Rupee",
            "MVR": "(MVR) Maldivian Rufiyaa",
            "MWK": "(MWK) Malawian Kwacha",
            "MXN": "(MXN) Mexican Peso",
            "MYR": "(MYR) Malaysian Ringgit",
            "MZN": "(MZN) Mozambican Metical",
            "NAD": "(NAD) Namibian Dollar",
            "NGN": "(NGN) Nigerian Naira",
            "NIO": "(NIO) Nicaraguan Córdoba",
            "NOK": "(NOK) Norwegian Krone",
            "NPR": "(NPR) Nepalese Rupee",
            "NZD": "(NZD) New Zealand Dollar",
            "OMR": "(OMR) Omani Rial",
            "PAB": "(PAB) Panamanian Balboa",
            "PEN": "(PEN) Peruvian Nuevo Sol",
            "PGK": "(PGK) Papua New Guinean Kina",
            "PHP": "(PHP) Philippine Peso",
            "PKR": "(PKR) Pakistani Rupee",
            "PLN": "(PLN) Polish Zloty",
            "PYG": "(PYG) Paraguayan Guarani",
            "QAR": "(QAR) Qatari Rial",
            "RON": "(RON) Romanian Leu",
            "RSD": "(RSD) Serbian Dinar",
            "RUB": "(RUB) Russian Ruble",
            "RWF": "(RWF) Rwandan Franc",
            "SAR": "(SAR) Saudi Riyal",
            "SBD": "(SBD) Solomon Islands Dollar",
            "SCR": "(SCR) Seychellois Rupee",
            "SDG": "(SDG) Sudanese Pound",
            "SEK": "(SEK) Swedish Krona",
            "SGD": "(SGD) Singapore Dollar",
            "SHP": "(SHP) Saint Helena Pound",
            "SLL": "(SLL) Sierra Leonean Leone",
            "SOS": "(SOS) Somali Shilling",
            "SRD": "(SRD) Surinamese Dollar",
            "STD": "(STD) São Tomé and Príncipe Dobra",
            "SVC": "(SVC) Salvadoran Colón",
            "SYP": "(SYP) Syrian Pound",
            "SZL": "(SZL) Swazi Lilangeni",
            "THB": "(THB) Thai Baht",
            "TJS": "(TJS) Tajikistani Somoni",
            "TMT": "(TMT) Turkmenistani Manat",
            "TND": "(TND) Tunisian Dinar",
            "TOP": "(TOP) Tongan Paʻanga",
            "TRY": "(TRY) Turkish Lira",
            "TTD": "(TTD) Trinidad and Tobago Dollar",
            "TWD": "(TWD) New Taiwan Dollar",
            "TZS": "(TZS) Tanzanian Shilling",
            "UAH": "(UAH) Ukrainian Hryvnia",
            "UGX": "(UGX) Ugandan Shilling",
            "USD": "(USD) United States Dollar",
            "UYU": "(UYU) Uruguayan Peso",
            "UZS": "(UZS) Uzbekistan Som",
            "VEF": "(VEF) Venezuelan Bolívar Fuerte",
            "VND": "(VND) Vietnamese Dong",
            "VUV": "(VUV) Vanuatu Vatu",
            "WST": "(WST) Samoan Tala",
            "XAF": "(XAF) CFA Franc BEAC",
            "XAG": "(XAG) Silver (troy ounce)",
            "XAU": "(XAU) Gold (troy ounce)",
            "XCD": "(XCD) East Caribbean Dollar",
            "XDR": "(XDR) Special Drawing Rights",
            "XOF": "(XOF) CFA Franc BCEAO",
            "XPF": "(XPF) CFP Franc",
            "YER": "(YER) Yemeni Rial",
            "ZAR": "(ZAR) South African Rand",
            "ZMK": "(ZMK) Zambian Kwacha (pre-2013)",
            "ZMW": "(ZMW) Zambian Kwacha",
            "ZWL": "(ZWL) Zimbabwean Dollar"
        }
    }

    function getCountries(){
        return {
        "Afghanistan": "Afghanistan",
        "Albania": "Albania",
        "Algeria": "Algeria",
        "American Samoa": "American Samoa",
        "Andorra": "Andorra",
        "Angola": "Angola",
        "Anguilla": "Anguilla",
        "Antarctica": "Antarctica",
        "Antigua and Barbuda": "Antigua and Barbuda",
        "Argentina": "Argentina",
        "Armenia": "Armenia",
        "Aruba": "Aruba",
        "Australia": "Australia",
        "Austria": "Austria",
        "Azerbaijan": "Azerbaijan",
        "Bahamas": "Bahamas",
        "Bahrain": "Bahrain",
        "Bangladesh": "Bangladesh",
        "Barbados": "Barbados",
        "Belarus": "Belarus",
        "Belgium": "Belgium",
        "Belize": "Belize",
        "Benin": "Benin",
        "Bermuda": "Bermuda",
        "Bhutan": "Bhutan",
        "Bolivia": "Bolivia",
        "BAH": "Bosnia and Herzegovina",
        "Botswana": "Botswana",
        "BI": "Bouvet Island",
        "Brazil": "Brazil",
        "BIOT": "British Indian Ocean Territory",
        "BD": "Brunei Darussalam",
        "Bulgaria": "Bulgaria",
        "BF": "Burkina Faso",
        "Burundi": "Burundi",
        "Cambodia": "Cambodia",
        "Cameroon": "Cameroon",
        "Canada": "Canada",
        "CV": "Cape Verde",
        "CI": "Cayman Islands",
        "CAR": "Central African Republic",
        "Chad": "Chad",
        "Chile": "Chile",
        "China": "China",
        "CHI": "Christmas Island",
        "CKI": "Cocos (Keeling) Islands",
        "Colombia": "Colombia",
        "Comoros": "Comoros",
        "Congo": "Congo",
        "CTDRT": "Congo, The Democratic Republic of The",
        "COI": "Cook Islands",
        "Costa Rica": "Costa Rica",
        "CDI": "Cote D'ivoire",
        "Croatia": "Croatia",
        "Cuba": "Cuba",
        "Cyprus": "Cyprus",
        "CR": "Czech Republic",
        "Denmark": "Denmark",
        "Djibouti": "Djibouti",
        "Dominica": "Dominica",
        "DR": "Dominican Republic",
        "Ecuador": "Ecuador",
        "Egypt": "Egypt",
        "ES": "El Salvador",
        "EG": "Equatorial Guinea",
        "Eritrea": "Eritrea",
        "Estonia": "Estonia",
        "Ethiopia": "Ethiopia",
        "FIM": "Falkland Islands (Malvinas)",
        "FI": "Faroe Islands",
        "Fiji": "Fiji",
        "Finland": "Finland",
        "France": "France",
        "FG": "French Guiana",
        "FP": "French Polynesia",
        "FST": "French Southern Territories",
        "Gabon": "Gabon",
        "Gambia": "Gambia",
        "Georgia": "Georgia",
        "Germany": "Germany",
        "Ghana": "Ghana",
        "Gibraltar": "Gibraltar",
        "Greece": "Greece",
        "Greenland": "Greenland",
        "Grenada": "Grenada",
        "Guadeloupe": "Guadeloupe",
        "Guam": "Guam",
        "Guatemala": "Guatemala",
        "Guinea": "Guinea",
        "GB": "Guinea-bissau",
        "Guyana": "Guyana",
        "Haiti": "Haiti",
        "HIAMI": "Heard Island and Mcdonald Islands",
        "HSVCT": "Holy See (Vatican City State)",
        "Honduras": "Honduras",
        "HK": "Hong Kong",
        "Hungary": "Hungary",
        "Iceland": "Iceland",
        "India": "India",
        "Indonesia": "Indonesia",
        "IIRO": "Iran, Islamic Republic of",
        "Iraq": "Iraq",
        "Ireland": "Ireland",
        "Israel": "Israel",
        "Italy": "Italy",
        "Jamaica": "Jamaica",
        "Japan": "Japan",
        "Jordan": "Jordan",
        "Kazakhstan": "Kazakhstan",
        "Kenya": "Kenya",
        "Kiribati": "Kiribati",
        "KDPR": "Korea, Democratic People's Republic of",
        "KRO": "Korea, Republic of",
        "Kuwait": "Kuwait",
        "Kyrgyzstan": "Kyrgyzstan",
        "LPDR": "Lao People's Democratic Republic",
        "Latvia": "Latvia",
        "Lebanon": "Lebanon",
        "Lesotho": "Lesotho",
        "Liberia": "Liberia",
        "LAJ": "Libyan Arab Jamahiriya",
        "Liechtenstein": "Liechtenstein",
        "Lithuania": "Lithuania",
        "Luxembourg": "Luxembourg",
        "Macao": "Macao",
        "MTFYRO": "Macedonia, The Former Yugoslav Republic of",
        "Madagascar": "Madagascar",
        "Malawi": "Malawi",
        "Malaysia": "Malaysia",
        "Maldives": "Maldives",
        "Mali": "Mali",
        "Malta": "Malta",
        "MI": "Marshall Islands",
        "Martinique": "Martinique",
        "Mauritania": "Mauritania",
        "Mauritius": "Mauritius",
        "Mayotte": "Mayotte",
        "Mexico": "Mexico",
        "MFSO": "Micronesia, Federated States of",
        "MRO": "Moldova, Republic of",
        "Monaco": "Monaco",
        "Mongolia": "Mongolia",
        "Montserrat": "Montserrat",
        "Morocco": "Morocco",
        "Mozambique": "Mozambique",
        "Myanmar": "Myanmar",
        "Namibia": "Namibia",
        "Nauru": "Nauru",
        "Nepal": "Nepal",
        "Netherlands": "Netherlands",
        "NA": "Netherlands Antilles",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "Nicaragua": "Nicaragua",
        "Niger": "Niger",
        "Nigeria": "Nigeria",
        "Niue": "Niue",
        "NI": "Norfolk Island",
        "NMI": "Northern Mariana Islands",
        "Norway": "Norway",
        "Oman": "Oman",
        "Pakistan": "Pakistan",
        "Palau": "Palau",
        "PTO": "Palestinian Territory, Occupied",
        "Panama": "Panama",
        "PNG": "Papua New Guinea",
        "Paraguay": "Paraguay",
        "Peru": "Peru",
        "Philippines": "Philippines",
        "Pitcairn": "Pitcairn",
        "Poland": "Poland",
        "Portugal": "Portugal",
        "PR": "Puerto Rico",
        "Qatar": "Qatar",
        "Reunion": "Reunion",
        "Romania": "Romania",
        "RF": "Russian Federation",
        "Rwanda": "Rwanda",
        "SH": "Saint Helena",
        "SKAN": "Saint Kitts and Nevis",
        "SL": "Saint Lucia",
        "SPAM": "Saint Pierre and Miquelon",
        "SVTAG": "Saint Vincent and The Grenadines",
        "Samoa": "Samoa",
        "SM": "San Marino",
        "STAP": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "Senegal": "Senegal",
        "SAM": "Serbia and Montenegro",
        "Seychelles": "Seychelles",
        "SIL": "Sierra Leone",
        "Singapore": "Singapore",
        "Slovakia": "Slovakia",
        "Slovenia": "Slovenia",
        "SI": "Solomon Islands",
        "Somalia": "Somalia",
        "SOA": "South Africa",
        "SGTSSI": "South Georgia and The South Sandwich Islands",
        "Spain": "Spain",
        "SRL": "Sri Lanka",
        "Sudan": "Sudan",
        "Suriname": "Suriname",
        "SJM": "Svalbard and Jan Mayen",
        "Swaziland": "Swaziland",
        "Sweden": "Sweden",
        "Switzerland": "Switzerland",
        "SAR": "Syrian Arab Republic",
        "Taiwan, Province of China": "Taiwan, Province of China",
        "Tajikistan": "Tajikistan",
        "TURO": "Tanzania, United Republic of",
        "Thailand": "Thailand",
        "TL": "Timor-leste",
        "Togo": "Togo",
        "Tokelau": "Tokelau",
        "Tonga": "Tonga",
        "TAT": "Trinidad and Tobago",
        "Tunisia": "Tunisia",
        "Turkey": "Turkey",
        "Turkmenistan": "Turkmenistan",
        "TCI": "Turks and Caicos Islands",
        "Tuvalu": "Tuvalu",
        "Uganda": "Uganda",
        "Ukraine": "Ukraine",
        "UAE": "United Arab Emirates",
        "UK" : "United Kingdom",
        "US": "United States",
        "USMOI": "United States Minor Outlying Islands",
        "Uruguay": "Uruguay",
        "Uzbekistan": "Uzbekistan",
        "Vanuatu": "Vanuatu",
        "Venezuela": "Venezuela",
        "Viet Nam": "Viet Nam",
        "VIB": "Virgin Islands, British",
        "VIUS": "Virgin Islands, U.S.",
        "WF": "Wallis and Futuna",
        "WS": "Western Sahara",
        "Yemen": "Yemen",
        "Zambia": "Zambia",
        "Zimbabwe": "Zimbabwe"
        }
    }
    function getAutoArchives() {
        return {
            "30": "30 days",
            "60": "60 days",
            "90": "90 days default"
        }
    }
    function getExchangeRate(purchaseDate, baseCurrency) {
        var methodCall = '/latest';
        var params = {app_id: APP_ID};

        if (new Date(purchaseDate) < new Date()) {
            methodCall = '/historical/' + purchaseDate.substring(0, 10);
        }


        if (baseCurrency) {
            params.base = baseCurrency;
        }

        return $http({
            method: 'GET',
            url: OPEN_EXCHANGE_API_URL + methodCall + '.json',
            params: params
        })
        .then(function(result) {
            return result.data;
        });
    }

    return {
        getCurrencies: getCurrencies,
        getCurrenciesWithAbbrName: getCurrenciesWithAbbrName,
        getExchangeRate: getExchangeRate,
        getAutoArchives: getAutoArchives,
        getCountries: getCountries
    }
});